// import java.util.*;
// public class ConditionalStatement{
//     public static void main(String args[]){
//         Scanner sc = new Scanner(System.in);
//         // int age = 6;
//         int age = sc.nextInt();
//         if(age>=18){
//             System.out.println("you re eligible for driving,vote");
//         }
//         else{
//             System.out.println("not eligible");
//         }
//     }
// }/

//  <<<  PRINT THE THE LARGEST OF 2 >>>
// import java.util.*;
// public class ConditionalStatement{
//     public static void main(String args[]){
//       int A = 1;
//       int B = 3;
//     if(A>=B){
//         System.out.println("A is largest of 2");
//     }  
//     else{
//         System.out.println("B is largest of 2");
//     } 
//     }
// }


//  <<< PRINT IF A NUMBER IS EVEN OR ODD
import java.util.*;
public class ConditionalStatement{
    public static void main(String args[]){
        Scanner sc = new Scanner (System.in);
        int number = sc.nextInt();

        if(number % 2 == 0){
            System.out.println("Even");
        }
        else{
            System.out.println("Odd");
        }      
        
    
    
    }
}